run:
  timeout: 5m
  issues-exit-code: 1
  tests: false
  allow-parallel-runners: true
  go: 1.24

linters-settings:
  gci:
    local-prefix: github.com/yitsushi/totp-cli
  goimports:
    local-prefix: github.com/yitsushi/totp-cli
  govet:
    shadow: true
  misspell:
    locale: US
  cyclop:
    max-complexity: 15
    skip-tests: true
  nolintlint:
    allow-leading-space: false
    allow-unused: false
    require-explanation: true
    require-specific: false
  varnamelen:
    ignore-names:
      - ns
      - err
      - iv
  depguard:
    rules:
      main:
        allow:
          - $gostd
          - filippo.io/age
          - github.com/urfave/cli/v2
          - github.com/yitsushi/totp-cli
          - github.com/kardianos/osext
          - github.com/yitsushi/github-release-check

issues:
  exclude-rules:
  - path: _test\.go
    linters:
    - goerr113
    - gocyclo
    - errcheck
    - gosec
    - dupl
    - funlen
    - scopelint
    - testpackage
    - varnamelen
  - path: internal/cmd/
    linters:
    - forbidigo
  - text: "sig: func github.com/yitsushi/totp-cli/"
    linters:
    - wrapcheck
  - text: "sig: func \\(\\*?github.com/yitsushi/totp-cli/"
    linters:
    - wrapcheck
  - path: internal/info
    linters:
    - gochecknoglobals
  - source: "// .* #\\d+"
    # Ignore TODO lines if they have a GitHub Issue reference.
    linters:
    - godox

linters:
  enable-all: true
  disable:
    # Deprecated
    - tenv          # Replaced by usetesting.

    # Disabled because I need naked return to handle extra errors in defer.
    - nakedret

    # Just disabled them...
    - exhaustruct

